name: Tests

# Controls when the action will run. 
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tests:
    # The type of runner that the job will run on
    runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
          
      # Run API unit tests
      - name: API Unit Tests
        run: dotnet test
        working-directory: API/Test.API
        
      # Run Front-end unit tests
      - name: Front-end Unit Tests
        run: |
          npm install
          npm test
        working-directory: react-frontend/src
